name: bookenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask
  - nltk
  - textblob
  - spacy
  - pytorch
  - transformers
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - PyPDF2
  - seaborn
  - pip
  - pip:
      - pdfplumber
